name: "Run Semgrep in Minikube"
description: "Trigger a Semgrep scan in your local Minikube cluster"
title: "[Semgrep Minikube] Scan Request"
labels: ["semgrep", "automation", "minikube"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Semgrep Minikube Deployment Request

        This issue will trigger a Semgrep scan in your local Minikube cluster using the Helm chart.

        **Note**: This workflow is configured for local deployment based on your preferences.

  - type: input
    id: workflow_trigger
    attributes:
      label: "Workflow Trigger"
      description: "This field helps identify the workflow to trigger"
      value: "semgrep-minikube"
    validations:
      required: true

  - type: input
    id: target_environment
    attributes:
      label: "Target Environment"
      description: "Which environment values should be used? (dev, beta, prod)"
      placeholder: "dev"
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: "Additional Notes"
      description: "Any extra information or context?"
      placeholder: "Optional"
    validations:
      required: false
