name: "Deploy Semgrep to Local Minikube"
description: "Deploy GitOps Semgrep to your local Minikube cluster"
title: ""
labels: ["semgrep", "minikube", "deployment"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Deploy Semgrep to Local Minikube

        This will generate the deployment commands for your local Minikube cluster.

        **Prerequisites:**
        - ✅ Minikube is running locally
        - ✅ Helm is installed
        - ✅ kubectl is configured for your Minikube cluster

  - type: dropdown
    id: environment
    attributes:
      label: "Environment"
      description: "Select the environment configuration to use"
      options:
        - "dev"
        - "beta"
        - "prod"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: scan_target
    attributes:
      label: "What to Scan"
      description: "Choose what Semgrep should scan"
      options:
        - "Frontend rules (JavaScript/TypeScript)"
        - "Backend rules (Java)"
        - "Shared rules (Common security)"
        - "All rules (Frontend + Backend + Shared)"
        - "Custom rules (specify in notes)"
      default: 3
    validations:
      required: true

  - type: input
    id: semgrep_token
    attributes:
      label: "Semgrep Token (Optional)"
      description: "Your Semgrep token for enhanced scanning (leave empty for basic scan)"
      placeholder: "your-semgrep-token-here"
    validations:
      required: false

  - type: checkboxes
    id: deployment_options
    attributes:
      label: "Deployment Options"
      description: "Select deployment preferences"
      options:
        - label: "Generate deployment commands only (recommended)"
          required: false
        - label: "Include cleanup commands"
          required: false
        - label: "Show logs after deployment"
          required: false

  - type: textarea
    id: custom_config
    attributes:
      label: "Custom Configuration (Optional)"
      description: "Any custom Helm values or configuration overrides"
      placeholder: |
        # Example:
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
      render: yaml
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: "Additional Notes"
      description: "Any additional context or requirements"
      placeholder: "Optional notes..."
    validations:
      required: false
