name: 🚀 Deploy Semgrep Application
description: Deploy Semgrep application to local Minikube cluster using ARC runners
title: "[DEPLOY] Deploy Semgrep to {{environment}}"
labels: ["deployment", "semgrep", "gitops"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Deploy Semgrep Application
        
        This will trigger an automated deployment of the Semgrep application to your local Minikube cluster using ARC self-hosted runners.

  - type: dropdown
    id: environment
    attributes:
      label: Target Environment
      description: Select the environment to deploy to
      options:
        - dev
        - beta
        - prod
      default: 0
    validations:
      required: true

  - type: input
    id: semgrep_token
    attributes:
      label: Semgrep App Token (Optional)
      description: Provide your Semgrep App Token for enhanced scanning capabilities
      placeholder: "semgrep_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    validations:
      required: false

  - type: dropdown
    id: branch
    attributes:
      label: Branch to Deploy
      description: Select the branch/ref to deploy from
      options:
        - main
        - develop
        - feature/latest
        - custom (specify below)
      default: 0
    validations:
      required: true

  - type: input
    id: custom_branch
    attributes:
      label: Custom Branch/Ref (if selected above)
      description: Specify custom branch, tag, or commit SHA
      placeholder: "feature/my-branch or v1.2.3 or abc123def"
    validations:
      required: false

  - type: checkboxes
    id: deployment_options
    attributes:
      label: Deployment Options
      description: Select additional deployment options
      options:
        - label: Wait for job completion
          required: false
        - label: Show detailed logs
          required: false
        - label: Cleanup previous deployments first
          required: false
        - label: Skip pre-deployment checks
          required: false

  - type: textarea
    id: additional_config
    attributes:
      label: Additional Configuration (Optional)
      description: Any additional Helm values or configuration overrides
      placeholder: |
        Example:
        resources.limits.cpu: "2"
        resources.limits.memory: "4Gi"
        semgrep.configPath: "/repo/rules/backend/"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Deployment Description
      description: Describe what you're deploying and why
      placeholder: "Deploying new Semgrep rules for frontend security scanning..."
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-deployment Checklist
      description: Confirm the following before deployment
      options:
        - label: Minikube is running locally
          required: true
        - label: ARC runners are healthy
          required: true
        - label: No conflicting deployments are running
          required: false
        - label: I have tested this configuration locally
          required: false
