# Production environment configuration
# Uses token from GitHub Secrets for production environment
environment: prod
github:
  repository: your-org/gitops-semgrep

semgrep:
  token: ${SEMGREP_TOKEN_PROD}
  configPath: /repo/rules/
  
# Additional configuration options
job:
  name: semgrep-scan-once
  restartPolicy: OnFailure
  
# Resource limits for production environment
resources:
  limits:
    cpu: "4"
    memory: "8Gi"
  requests:
    cpu: "2"
    memory: "4Gi"
