name: Cleanup Semgrep Deployments

on:
  workflow_dispatch:
    inputs:
      cleanup_all:
        description: 'Cleanup all Semgrep deployments'
        required: true
        default: false
        type: boolean

jobs:
  cleanup:
    runs-on: arc-runner-set
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check Minikube connectivity
        run: |
          echo "=== Checking Minikube connectivity ==="
          kubectl cluster-info
          kubectl get nodes
          
      - name: List current Semgrep deployments
        run: |
          echo "📋 Current Semgrep deployments:"
          helm list -A | grep semgrep || echo "No Semgrep deployments found"
          kubectl get jobs -l app=semgrep || echo "No Semgrep jobs found"
          kubectl get pods -l app=semgrep || echo "No Semgrep pods found"
          
      - name: Cleanup Semgrep deployments
        run: |
          echo "🧹 Cleaning up Semgrep deployments..."
          
          # Uninstall Helm releases
          helm uninstall semgrep-scan || echo "No semgrep-scan release found"
          
          # Clean up any remaining jobs
          kubectl delete jobs -l app=semgrep || echo "No jobs to delete"
          
          # Clean up any remaining pods
          kubectl delete pods -l app=semgrep || echo "No pods to delete"
          
          echo "✅ Cleanup completed!"
          
      - name: Verify cleanup
        run: |
          echo "📋 Verifying cleanup..."
          helm list -A | grep semgrep || echo "✅ No Semgrep Helm releases found"
          kubectl get jobs -l app=semgrep || echo "✅ No Semgrep jobs found"
          kubectl get pods -l app=semgrep || echo "✅ No Semgrep pods found"
