name: Deploy Semgrep to Local Minikube

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - beta
        - prod
      semgrep_token:
        description: 'Semgrep App Token (optional)'
        required: false
        type: string

jobs:
  deploy-semgrep:
    runs-on: arc-runner-set
    environment: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify runner environment
        run: |
          echo "🎉 Running on ARC self-hosted runner!"
          echo "Runner name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "Event: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref_name }}"



      # - name: Check Minikube connectivity
      #   run: |
      #     echo "=== Checking Minikube connectivity ==="
      #     kubectl cluster-info
      #     kubectl get nodes
      #     echo "✅ Minikube is accessible"

      - name: Set deployment environment
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "DEPLOY_ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
            echo "SEMGREP_TOKEN=${{ github.event.inputs.semgrep_token }}" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" = "main" ]; then
            echo "DEPLOY_ENV=prod" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" = "develop" ]; then
            echo "DEPLOY_ENV=beta" >> $GITHUB_ENV
          else
            echo "DEPLOY_ENV=dev" >> $GITHUB_ENV
          fi

      - name: Deploy Semgrep application
        run: |
          echo "🚀 Deploying Semgrep to environment: $DEPLOY_ENV"
          chmod +x ./deploy-local.sh

          if [ -n "$SEMGREP_TOKEN" ]; then
            ./deploy-local.sh "$DEPLOY_ENV" "$SEMGREP_TOKEN"
          else
            ./deploy-local.sh "$DEPLOY_ENV"
          fi

      - name: Verify deployment
        run: |
          echo "📊 Checking deployment status..."
          kubectl get jobs -l app=semgrep
          kubectl get pods -l app=semgrep

          echo "📋 Waiting for job to complete..."
          kubectl wait --for=condition=complete job/semgrep-scan --timeout=300s || true

      - name: Show deployment logs
        if: always()
        run: |
          echo "📋 Semgrep job logs:"
          kubectl logs job/semgrep-scan || echo "No logs available yet"

      - name: Cleanup on failure
        if: failure()
        run: |
          echo "🧹 Cleaning up failed deployment..."
          helm uninstall semgrep-scan || true
