name: Test ARC Runner

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: arc-runner-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Test runner
        run: |
          echo "🎉 Running on ARC self-hosted runner!"
          echo "Runner name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
          echo "Runner architecture: $RUNNER_ARCH"
          echo "Workspace: $GITHUB_WORKSPACE"
          
      - name: System info
        run: |
          echo "=== System Information ==="
          uname -a
          echo "=== Available tools ==="
          which docker || echo "Docker not available"
          which kubectl || echo "kubectl not available"
          which helm || echo "Helm not available"
          
      - name: Test Minikube connectivity
        run: |
          echo "=== Testing Minikube connectivity ==="
          kubectl cluster-info || echo "Cannot connect to Minikube"
          kubectl get nodes || echo "Cannot get nodes"
